language: cpp
compiler: gcc
os: linux

branches:
    only:
        - travis

before_install:
    - echo Install dependencies

install:
    - mkdir -p build/libindi
    - cd build/libindi
    - cmake . ../../libindi/
    - make
    
script:
    - echo Test
    

