language: cpp
compiler: gcc
os: linux
sudo: false
dist: trusty


cache: apt
addons:
  apt:
    packages:
    - libusb-1.0-0-dev
    - libcfitsio3-dev
    - libnova-dev
    - libgphoto2-dev
    - libgps-dev
    - libjpeg-dev
    - libopenal-dev

branches:
    only:
        - travis

before_install:
    - echo Install dependencies

install:
    - mkdir -p build/libindi
    - cd build/libindi
    - cmake . ../../libindi/
    - make
    
script:
    - echo Test
    

