version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Check env
          command: ls -l
      - run:
          name: Install deps
          command: sudo apt update && sudo apt -y install cmake
      - run: 
          name: Install toolchain
          command: sudo apt -y full-upgrade


