version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Check env
          command: ls -l
      - run:
          name: Install deps
          command: .circleci/deps-linux.sh
      - run: 
          name: Build core
          command: .circleci/build-core.sh
      - run: 
          name: Build libs
          command: .circleci/build-libs.sh
      - run: 
          name: Build 3rd party drivers
          command: .circleci/build-3rdparty.sh


