version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Check env
          command: ls -l
      - run:
          name: Install deps
          command: sudo apt update && sudo apt install cmake

